### ISSUE TITLE
TODO: Concept finalization

### ISSUE THREAD

**Issue by jawhinge** [teh-te4-tekh-team/Unity-Game#1]
Discuss with Merreh:

- [ ] Player model
- [ ] Weapons
- [x] Map design 
- [ ] Menu design
- [ ] Overall visual conceptualization of the game (colors/moods/impressions/stuffidk)

Discuss locally:

- [ ] Story points 
- [ ] Tutorial
- [ ] User experience (pre-game start)
- [ ] Enemy spawning and mechanics
- [ ] Player movement and mechanics
- [ ] Interaction with the environment
- [ ] Player class definitions and interactions
- [ ] Multiplayer (finally)

FULL DESCRIPTION: https://docs.google.com/document/d/1r7Yk4HvwIxrEwIxyvVBCh11gtufWmvL8T7ZQ9_oomJ0/edit?usp=sharing
